### ISSUE TITLE
关于语音的问题

### ISSUE THREAD

**Issue by Brannua** [tsq/youdao-cli-translator#5]
- 大佬您好，您的工具很实用～
- 有一个小问题如下：
    - 有道智云对110错误码的解释是应用没有绑定 tts 实例，经过测试确实可以成功翻译了，但是 tts 是语音相关的，这款工具可以将翻译的单词读出来吗，有没有参数可以设置，期待您的热心回复，谢谢

**Comment by tsq** [comment]
@Brannua 你好，这款工具没有将翻译单词读出来的功能。  

API确实返回了一个speakUrl字段用于发音功能，
```
speakUrl:
   'http://openapi.youdao.com/ttsapi?q=hello&langType=en&sign=4624A8CEE0DDEAAD004218E1C586DF76&salt=1616110023603&voice=4&format=mp3&appKey=295d58dc4f493d2c&ttsVoiceStrict=false'
```

但是当初自己测试的也和你说的一样，只要打开这个url返回的都是110错误码，后面我也没有仔细研究为什么会出现这种错误，所以发音功能就没加了！

**Comment by Brannua** [comment]
感谢



---原始邮件---
发件人: "TANG SHI ***@***.***&gt;
发送时间: 2021年3月19日(周五) 上午7:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tsq/youdao-cli-translator] 关于语音的问题 (#5)




 
@Brannua 你好，这款工具没有将翻译单词读出来的功能。
 
API确实返回了一个speakUrl字段用于发音功能，
 speakUrl:    'http://openapi.youdao.com/ttsapi?q=hello&amp;langType=en&amp;sign=4624A8CEE0DDEAAD004218E1C586DF76&amp;salt=1616110023603&amp;voice=4&amp;format=mp3&amp;appKey=295d58dc4f493d2c&amp;ttsVoiceStrict=false'  
但是当初自己测试的也和你说的一样，只要打开这个url返回的都是110错误码，后面我也没有仔细研究为什么会出现这种错误，所以发音功能就没加了！
